Refactor MeshTopology to add AbstractMeshTopology
AbstractMeshTopology contains general methods and properties common to any meshtopology.

`MeshTopology` and `VertexOnlyMeshTopology` and now subclasses of `AbstractMeshTopology`.

Instances of `MeshTopology` and `VertexOnlyMeshTopology` each call the `__init__` method of their parent class at the beginning of their `__init__` methods.

Much of DMSwarm.pyx has been moved to dmplex.pyx and various checks have been added to dmplex.pyx to make it work more generally.

NOTE: Also allow attribute error in test_fs_caching.py gc.get_objects()

Presumably because of a python 3.6 bug the `howmany(cls)` function would fail when doing `isinstance(x, cls)` with

```
AttributeError: 'functools._lru_list_elem' object has no attribute '__class__'
```

This does not occur in subsequent python versions and is not important for the test so the error is excepted alongside the existing `ReferenceError` except.